// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetUser struct {
	UserID    int    `json:"UserId"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Mobile    string `json:"mobile"`
	Email     string `json:"email"`
	Created   string `json:"created"`
	Status    string `json:"status"`
}

type Login struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	Tenanttoken string `json:"tenanttoken"`
}

type LoginData struct {
	Status     bool          `json:"status"`
	Code       int           `json:"code"`
	Message    string        `json:"message"`
	UserInfo   *UserData     `json:"userInfo"`
	Tenantinfo []*Tenantdata `json:"tenantinfo"`
}

type NewUser struct {
	Firstname   string `json:"firstname"`
	Lastname    string `json:"lastname"`
	Email       string `json:"email"`
	Password    string `json:"password"`
	Mobile      string `json:"Mobile"`
	Roleid      int    `json:"roleid"`
	Referenceid int    `json:"referenceid"`
	Locationid  int    `json:"locationid"`
	Configid    int    `json:"configid"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Reset struct {
	Password string `json:"password"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UserCreatedData struct {
	Status   bool      `json:"status"`
	Code     int       `json:"code"`
	Message  string    `json:"message"`
	UserInfo *UserData `json:"userInfo"`
}

type UserData struct {
	UserID      int     `json:"UserId"`
	Firstname   string  `json:"Firstname"`
	Lastname    string  `json:"Lastname"`
	Email       string  `json:"Email"`
	Mobile      string  `json:"Mobile"`
	Roleid      *int    `json:"Roleid"`
	Configid    *int    `json:"Configid"`
	Token       string  `json:"Token"`
	Tenantid    *int    `json:"Tenantid"`
	Tenantname  *string `json:"Tenantname"`
	Locationid  *int    `json:"Locationid"`
	Opentime    *string `json:"Opentime"`
	Closetime   *string `json:"Closetime"`
	CreatedDate string  `json:"CreatedDate"`
	Status      string  `json:"Status"`
}

type Tenantdata struct {
	Subscriptionid int    `json:"Subscriptionid"`
	Packageid      int    `json:"Packageid"`
	Packagename    string `json:"Packagename"`
	Moduleid       int    `json:"Moduleid"`
	Modulename     string `json:"Modulename"`
}

type Updateddata struct {
	Status  bool   `json:"status"`
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Userupdateinput struct {
	Userid    int    `json:"userid"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	Contactno string `json:"contactno"`
}
